cocowwy:
  dingding:
    robots:
      - label: label1
        signature: 群a的机器人的signature
        webhook: 群a的机器人的Webhook
      - label: label1
        signature: 群b的机器人的signature
        webhook: 群b的机器人的Webhook
      - label: label2
        signature: 群c的机器人的signature
        webhook: 群c的机器人的Webhook

server:
  port: 8081