dingding:
  robots:
    robot:
      - label:
        agentId:
        appKey:
        appSecret:
        # 机器人Token缓存时长，默认110min
        tokenRefresh:
    hooks:
      - label:
        signature:
        webhook:

server:
  port: 9001